name: Sync

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository != 'ph00lt0/blocklist'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name 'ph00lt0 Blocklist'
          git config user.email '-'

      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/ph00lt0/blocklist.git
          git fetch upstream

      - name: Sync and squash
        env:
          TARGET_BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          git checkout "$TARGET_BRANCH"
          git reset --hard "upstream/$TARGET_BRANCH"
          git add -A
          git checkout --orphan temp
          git commit -m "Blocklist release"
          git branch -D "$TARGET_BRANCH"
          git branch -m "$TARGET_BRANCH"
          git push -f origin "$TARGET_BRANCH"
